[package]
name = "helloworld_trusted"
version = "1.0.0"

[lib]
name = "helloworld_trusted"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
sgx_types = { path = "/opt/rust-sgx-sdk/sgx_types" }
sgx_tstd = { path = "/opt/rust-sgx-sdk/sgx_tstd" }
